#! /bin/bash

gflag=0
aflag=0
mflag=0
bflag=0
dflag=0
aval=0000-00-00
bval=9999-99-99
debug=False
gvalin=''
gval='.*'
dir=$(pwd)
tail=1


ArgError() {
    if [ "$gflag" -gt 1 ]; then
        err=1
    fi

    if [ "$mflag" -gt 1 ]; then
        err=1
    fi

    if [ "$aflag" -gt 1 ]; then
        err=1
    fi

    if [ "$bflag" -gt 1 ]; then
        err=1
    fi

    if [ "$dflag" -gt 1 ]; then
        err=1
    fi

    #d and g use at the same time
    if [ "$dflag" -gt 0 ] && [ "$gflag" -gt 0 ]; then
        err=1
    fi

    if [ -n "$err" ]; then
        ERROR "Iilegal combination of options."
    fi
}

DEBUG() {
    if [ $debug == True ]; then
        echo "DEBUG: ""$1"
    fi
}

ERROR() {
    echo >&2 "ERROR: ""$1"
    exit 1
}

SecretArgCheck() {

    if [[ "$gflag" -gt 0 || "$mflag" -gt 0 || "$dflag" -gt 0 ]]; then

        ERROR "Option secret-log does not support -g option."
    fi
}

ListArgCheck() {

    if [ "$mflag" -gt 0 ]; then

        ERROR "Option secret-log does not support -g option."

    fi
}

HelpArgCheck() {

    if [[ $gflag -gt 0 || $mflag -gt 0 || $aflag -gt 0 || $bflag -gt 0 || $dflag -gt 0 ]]; then
        ERROR "Ilegal combination of options."
    fi
}

FileArgCheck() {

    if [[ $mflag -gt 0 || $aflag -gt 0 || $bflag -gt 0 || $dflag -gt 0 ]]; then
        ERROR "Ilegal combination of options."
    fi
}

CreateMoleRC() {
    #create mole_rc
    realmole=$(realpath "$MOLE_RC" 2>/dev/null)
    if [[ -z $realmole ]]; then
        ERROR "MOLE_RC not found"
    fi

    if [[ ! -e $realmole ]]; then
        touch "$realmole"
    fi
}

PrintHelp() {
    printf "
NAME 
    Makes One’s Life Easier
SYNOPSIS:
    mole -h
    mole [-g GROUP] FILE
    mole [-m] [FILTERS] [DIRECTORY]
    mole list [FILTERS] [DIRECTORY]

OPTIONS
    mole -h
        -h Display help information.

    mole [-g GROUP] FILE \t Opens the specified FILE.
        -g \t \t \t File will be assigned to a group named GROUP.

    mole [-m] [FILTERS] [DIRECTORY] \t  Selects a file from DIRECTORY to open
        - -m \t \t \t Selects the file that was opened most frequently.
        - if no directory is specified, the current directory is assumed
      
    mole list [FILTERS] [DIRECTORY] \t  Displays a list of files that were opened
        - if no directory is specified, the current directory is assumed. 
        
 FILTERS
    [-g GROUP1[,GROUP2[,...]]] - Specifies groups.
    [-d] - Records of files that has no GROUP specified.
    Options -d and -g cannot be used together.
    [-a DATE] - Records of files opened (edited) before this date will not be considered.
    [-b DATE] - Records of files opened (edited) after this date will not be considered.
    The DATE argument is in the format YYYY-MM-DD.\n"
    exit 0
}

SetEditor() {
    if [ -n "$EDITOR" ]; then
        editor_path="$EDITOR"

    elif [ -n "$VISUAL" ]; then
        editor_path="$VISUAL"
    else
        editor_path=$(which vi)
    fi
}

IsFile() {
    DEBUG "Given path $givenpath"
    if [ -d "$givenpath" ]; then
        DEBUG "Directory is $givenpath"
    elif [ -f "$givenpath" ]; then
        is_file=1
        DEBUG "File is $givenpath"
    else
        lastchar=${givenpath: -1}
        if [ "$lastchar" == "/" ]; then
            ERROR "NonExisting Directory is $givenpath"
        elif [ -n "$lastchar" ]; then
            is_file=1
            DEBUG "NonExisting File is $givenpath"
        fi
    fi
}

RunEditor() {
    if [ -n "$is_file" ]; then
        "$editor_path" "$givenpath"
    elif [ -n "$path" ]; then
        "$editor_path" "$path"
    else
        ERROR "Nothing matches given parameters"
    fi
}

GetTimestampDate() {
    date=$(date +'%Y-%m-%d')
    datetime=$(date +'%Y-%m-%d_%H-%M-%S')
    timestamp=$(date +%s)
}

UpdateRow() {
    GetTimestampDate
    IFS=',' read -ra rowarr <<<"$row"
    rowarr[2]="$date"
    rowarr[3]="$timestamp"
    rowarr[6]="$datetime"
    row=$(
        IFS=','
        echo "${rowarr[*]}"
    )
    echo "$row" >>"$realmole"
}

GetAwkRow() {
    AWKROWBASE="cat $realmole | awk -F ',' '\$3 > \"$aval\" && \$3 < \"$bval\" && \$2~g  && \$5~p {print \$0}' g=\"$gval\"  p=\"^$path$\""

    if [ ! "$is_list" ]; then
        if [ "$mflag" -eq 0 ]; then
            #noMflag
            AWKROWTAIL=" | sort -k4 -t ',' -n | tail -$tail| head -n 1"
        else
            AWKROWTAIL=" |sort -k1 -t ',' -n  | tail -$tail |head -n 1 "
        fi
    fi
    awkgetrow=$AWKROWBASE$AWKROWTAIL
    DEBUG "$awkgetrow"

    row=$(eval "$awkgetrow")

    if [ -z "$row" ]; then
        ERROR "Nothing matches given parameters."
    fi

}

GetAwkPath() {
    awkpath="awk -F ',' '{print \$1}'<<< $row"
    path=$(eval "$awkpath")
    DEBUG "Getawkpath: $path"
}

SetPath() {
    if [ -z "$givenpath" ]; then
        path=$(pwd)
        path=$(realpath "$path" 2>/dev/null)
        DEBUG "DIR: $path"
    else

        path=$(realpath "$givenpath" 2>/dev/null)

    fi
}

GetGroups() {

    IFS=',' read -ra groups <<<"$gval"
    if [ -z "$gval" ]; then
        gval="^$|"
    else
        gval=""
    fi

    for group in "${groups[@]}"; do

        gval+="^$group$|"
    done
    #always false
    gval+="/(?=a)b/"
}
GetExistingFile() {

    mole_rc_count=$(wc -l "$realmole" | awk '{print $1}')

    if [ "$tail" -eq "$mole_rc_count" ]; then
        ERROR "Nothing matches given parameters."
    fi

    if [ ! -f "$path" ]; then
        DEBUG "File $path does not exist"

        tail=$((tail + 1))
        GetFile
    fi

}
GetFile() {
    SetPath
    GetAwkRow
    GetAwkPath
    GetExistingFile
}
Directory() {
    DEBUG "In directory"
    GetGroups
    GetFile

    UpdateRow
    RunEditor
}

CheckForCommas() {

    if [[ "$gval" == *","* ]]; then
        ERROR "Commas are not allowed in group name."
    fi
}

AddRow() {
    realpath=$(realpath "$givenpath" 2>/dev/null)
    file=$(basename "$realpath")
    dir=$(dirname "$realpath")
 
    echo "$realpath,$gvalin,$date,$timestamp,$dir,$file,$datetime" >>"$realmole"
}

File() {
    GetTimestampDate
    CheckForCommas
    AddRow
    RunEditor
}
PrintList() {
    list=$(echo "$row" | cut -d ',' -f 2,6 | sort -f -d | uniq | awk -F ',' '{
  paths[$2][length(paths[$2])] = $1
} END {
  for (path in paths) {
    count = 0
    printf("%s: ;", path)
    comma = ""

    for (i = 0; i < length(paths[path]); i++) {
      if (paths[path][i] != "") {
        count++
        printf("%s%s", comma, paths[path][i])
        comma = ","
      }
    }

    if (count == 0) {
      printf("-")
    }

    print ""
  }
}' | column -t -s ";" | sed 's/ //1' | sort -f -d)
    echo "$list"
}

List() {
    SetPath
    GetGroups
    GetAwkRow
    PrintList

}

GetDirectories() {
    count=0
    for directory in "${dirarray[@]}"; do
        count+=1
        real=$(realpath "$directory" 2>/dev/null)

        if [ -d "$real" ]; then
            dirregex+="^$real$|"
        fi

    done
    if [ 0 -eq "$count" ]; then
        dirregex="^.*$|"
    fi
    #always false
    dirregex+="/(?=a)b/"
    AWKROWBASE="cat $realmole | awk -F ',' '\$3 > \"$aval\" && \$3 < \"$bval\" && \$5~p {print \$1 \";\" \$7}'  p=\"$dirregex\""

    dirrows=$(eval "$AWKROWBASE")
    if [ -z "$dirrows" ]; then
        ERROR "Nothing matches parameters"
    fi

}

CreateSecretOutput() {
    tozip=$(echo "$dirrows" | sort | awk -F';' '{ dates[$1] = dates[$1] ";" $2 
    } END {
     for (path in dates) {
        sub(/^;/, "", dates[path]); print path ";" dates[path] 
    } 
    }' | sort -f -d)

}

Zip() {
    GetTimestampDate
    if [ ! -d "$HOME/.mole/" ]; then
        mkdir -p "$HOME/.mole"
    fi
    $(bzip2 <<< "$tozip" > "$HOME/.mole/log_"$USER"_"$datetime".bz2")
}
Secret() {
    GetDirectories
    CreateSecretOutput
    Zip
}

Exec() {

    if [ -n "$is_secretlog" ]; then
        SecretArgCheck

        Secret
    elif [ -n "$is_list" ]; then
        ListArgCheck
        List
    else
        IsFile
        if [ -n "$is_file" ]; then
            FileArgCheck
            File
        else
            Directory
        fi
    fi
}

GetRealPath() {

    if [ -z "$givenpath" ]; then
        givenpath=$(pwd)
    fi

    givenpath=$(realpath "$givenpath" 2>/dev/null)
    if [ -z "$givenpath" ]; then
        ERROR "Given path $givenpath is not valid."
    fi
}

CheckRealPath() {
    is_realpath=$(command -v realpath)
    if [ -z "$is_realpath" ]; then
        ERROR "Utility realpath could not be found."
    fi
}

CheckDateFormat() {

    if [ $aflag -gt 0 ]; then
        if ! date -d "$aval" +"%Y-%m-%d" >/dev/null 2>&1; then

            ERROR "After date $aval is not in YYYY-MM-DD format."
        fi
    fi

    if [ $bflag -gt 0 ]; then
        if ! date -d "$bval" +"%Y-%m-%d" >/dev/null 2>&1; then

            ERROR "Before date $bval is not in YYYY-MM-DD format."
        fi
    fi

}

if [ "$1" = "list" ]; then
    is_list=1
    shift

fi

if [ "$1" = "secret-log" ]; then
    is_secretlog=1
    shift

fi
while getopts dhg:mb:a: name; do
    case $name in
    h)
        HelpArgCheck
        PrintHelp
        ;;
    g)
        gflag+=1
        gvalin="$OPTARG"
        if [ -n "$OPTARG" ]; then
            gval="$OPTARG"
        fi

        ;;
    m)
        mflag+=1
        ;;
    a)
        aflag+=1
        aval="$OPTARG"
        CheckDateFormat
        ;;
    b)
        bflag+=1
        bval="$OPTARG"
        CheckDateFormat
        ;;
    d)
        dflag+=1
        gval=''
        ;;
    ?)
        ERROR "Unknown option use mole -h to see usage."
        ;;
    esac
done
shift "$((OPTIND - 1))"

if [ -n "$is_secretlog" ]; then
    while [ $# -gt 0 ]; do
        dirarray+=("$1")
        shift
    done
fi

CheckRealPath
CreateMoleRC
givenpath=$1

GetRealPath

ArgError
SetEditor
DEBUG "Using: $editor_path"
Exec

exit 0
